### ISSUE TITLE
.

### ISSUE THREAD

**Issue by Bauuuuu** [SlimRoms/platform_manifest#26]
.

**Comment by PRJosh** [comment]
What?

**Comment by Bauuuuu** [comment]
there is typo in kernel code. Search "PRIOIRTY" word you will find it out

**Comment by PRJosh** [comment]
Then do the issue with the kernel not here :p 

https://source.codeaurora.org/external/gigabyte/kernel/msm/tree/drivers/media/platform/msm/vidc/vidc_hfi_api.h?h=caf/LA.BF.1.1.3_rb1.12#n724
