### ISSUE TITLE
empty framework_slim folder

### ISSUE THREAD

**Issue by m1omoe** [SlimRoms/platform_manifest#31]
vendor/slim/config/common.mk:96: error: frameworks/slim/slim_framework.mk: No such file or directory
13:42:26 dumpvars failed with: exit status 1

when i was building slim android9 it shows this, and  Slim/frameworks/slim is empty.

**Comment by luke-apk** [comment]
I guess you could comment out **line 96** in vendor/slim/config/common.mk for now and it should build the ROM. My guessing is that Slim Framework isn't ready yet.

**Comment by m1omoe** [comment]
@turboexperience Thanks to your remind. I will have a try.
